## Timestamp

pd.Timestamp('mm/dd/yyyy hh:mm AM/PM'): -> Timestamp('yyyy-mm-dd hh:mm:ss')
pd.Timestamp(yyyy, mm, dd, hh, mm): -> pd.Timestamp(yyyy, mm, dd, hh, mm)
pd.Timestamp(yyyy, mm, dd, hh, mm): -> [1,7]:[1: Monday, ...,  7: Sunday]
pd.Timestamp(yyyy, mm, dd, hh, mm, ss).year/month/day/hour/minute/second

## Period

pd.Period('mm/dd/yyyy') -> Period('yyyy-mm-dd', 'D')
pd.Period('mm/yyyy') -> Period('yyyy-mm', 'M')
pd.Period('yyyy') -> Period('yyyy', 'Y')

pd.Period(..anything..) [-, +] n ->D/M/Y [before,after] the date by n D/M/Y s

pd.Series(
    [A,B,C],
    [
        pd.Timestamp('yyy1-m1-d1'),
        pd.Timestamp('yyy2-m2-d2'), 
        pd.Timestamp('yyy3-m3-d3')
    ]
)
->
'yyy1-m3-d1'    A
'yyy2-m2-d2'    B
'yyy3-m1-d3'    C
obj



pd.Series(
    [A,B,C],
    [
        pd.Period('yyy1-m1-d1'),
        pd.Period('yyy2-m2-d2'), 
        pd.Period('yyy3-m3-d3')
    ]
)
->
'yyy1-m3-d1'    A
'yyy2-m2-d2'    B
'yyy3-m1-d3'    C
Freq: M, dtype: object

## Converting to Datetime

datetime = pd.to_datetime(date/time, dayfirst=True/yearfirst=True): -> Timestamp()

## Timedelta

pd.Timestamp('9/3/2016') - pd.Timestamp('9/1/2016') ->
Timedelta('2 days 00:00:00')

pd.Timestamp('9/2/2016 8:10AM') + pd.Timedelta('12D 3H') ->
Timestamp('2016-09-14 11:10:00')

## Offset

pd.Timestamp('9/4/2016').weekday() -> 6

In [2]:
# Now we can now add the timestamp with a week ahead
import pandas as pd
pd.Timestamp('9/4/2016') + pd.offsets.Week()

Timestamp('2016-09-11 00:00:00')

In [3]:
# Now let's try to do the month end, then we would have the last day of Septemer
pd.Timestamp('9/4/2016') + pd.offsets.MonthEnd()

Timestamp('2016-09-30 00:00:00')

## Working with Dates in a Dataframe

In [ ]:
# Next, let's look at a few tricks for working with dates in a DataFrame. Suppose we want to look at nine
# measurements, taken bi-weekly, every Sunday, starting in October 2016. Using date_range, we can create this
# DatetimeIndex. In data_range, we have to either specify the start or end date. If it is not explicitly
# specified, by default, the date is considered the start date. Then we have to specify number of periods, and
# a frequency. Here, we set it to "2W-SUN", which means biweekly on Sunday

dates = pd.date_range('10-01-2016', periods=9, freq='2W-SUN')
dates

DatetimeIndex(['2016-10-02', '2016-10-16', '2016-10-30', '2016-11-13',
               '2016-11-27', '2016-12-11', '2016-12-25', '2017-01-08',
               '2017-01-22'],
              dtype='datetime64[ns]', freq='2W-SUN')

In [ ]:
# There are many other frequencies that you can specify. For example, you can do business day
pd.date_range('10-01-2016', periods=9, freq='B')

DatetimeIndex(['2016-10-03', '2016-10-04', '2016-10-05', '2016-10-06',
               '2016-10-07', '2016-10-10', '2016-10-11', '2016-10-12',
               '2016-10-13'],
              dtype='datetime64[ns]', freq='B')

In [ ]:
# Or you can do quarterly, with the quarter start in June
pd.date_range('04-01-2016', periods=12, freq='QS-JUN')

DatetimeIndex(['2016-06-01', '2016-09-01', '2016-12-01', '2017-03-01',
               '2017-06-01', '2017-09-01', '2017-12-01', '2018-03-01',
               '2018-06-01', '2018-09-01', '2018-12-01', '2019-03-01'],
              dtype='datetime64[ns]', freq='QS-JUN')

In [ ]:
# Now, let's go back to our weekly on Sunday example and create a DataFrame using these dates, and some random
# data, and see what we can do with it.

dates = pd.date_range('10-01-2016', periods=9, freq='2W-SUN')
df = pd.DataFrame({'Count 1': 100 + np.random.randint(-5, 10, 9).cumsum(),
                  'Count 2': 120 + np.random.randint(-5, 10, 9)}, index=dates)
df

            Count 1  Count 2
2016-10-02      104      118
2016-10-16      109      117
2016-10-30      113      127
2016-11-13      110      116
2016-11-27      118      124
2016-12-11      124      116
2016-12-25      128      127
2017-01-08      127      129
2017-01-22      135      125

In [ ]:
# First, we can check what day of the week a specific date is. For example, here we can see that all the dates
# in our index are on a Sunday. Which matches the frequency that we set
df.index.weekday

Index([6, 6, 6, 6, 6, 6, 6, 6, 6], dtype='int32')

In [ ]:
# We can also use diff() to find the difference between each date's value.
df.diff()

            Count 1  Count 2
2016-10-02      NaN      NaN
2016-10-16      5.0     -1.0
2016-10-30      4.0     10.0
2016-11-13     -3.0    -11.0
2016-11-27      8.0      8.0
2016-12-11      6.0     -8.0
2016-12-25      4.0     11.0
2017-01-08     -1.0      2.0
2017-01-22      8.0     -4.0

In [ ]:
# Suppose we want to know what the mean count is for each month in our DataFrame. We can do this using
# resample. Converting from a higher frequency from a lower frequency is called downsampling (we'll talk about
# this in a moment)
df.resample('M').mean()

C:\Users\Abobaker\AppData\Local\Temp\ipykernel_8028\3536230891.py:4: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df.resample('M').mean()

               Count 1     Count 2
2016-10-31  108.666667  120.666667
2016-11-30  114.000000  120.000000
2016-12-31  126.000000  121.500000
2017-01-31  131.000000  127.000000

In [ ]:
# Or we can do it from a particular month
df['2016-12']

KeyError: '2016-12'

In [ ]:
# Or we can even slice on a range of dates For example, here we only want the values from December 2016
# onwards.
df['2016-12':]

            Count 1  Count 2
2016-12-11      124      116
2016-12-25      128      127
2017-01-08      127      129
2017-01-22      135      125